### ISSUE TITLE
[Bug] Unable to Save Draft

### ISSUE THREAD

**Issue by Nick-C** [osTicket/osTicket#1189]
Been having this issue for a while now and others have confirmed they see it too, I think it is Chrome and FF specific as it doesn't happen to us when using IE8.

Possibly something to do with redactor maybe as this seems to be where the popup is generated from and has been around since at least 1.9.1 I think.

Host environment doesn't seem to be an issue as I've had this happen with IIS and others have reported it on various linux environments too.

It was initially brought up here but got marked as a question rather than a bug/issue #1039 

And confirmed by others on the forums here:

http://osticket.com/forum/discussion/77841/error-when-looking-at-open-tickets-in-chrome

and here

http://osticket.com/forum/discussion/comment/82891

![2014-06-26_18-20-08](https://cloud.githubusercontent.com/assets/45155/4060561/b881fe36-2df0-11e4-9dcc-0a88d1c5becb.png)

![2014-08-27_14-48-07](https://cloud.githubusercontent.com/assets/45155/4060569/d1abe750-2df0-11e4-9c33-2703efc2f337.png)

Hopefully we can get this acknowledged as a bug and fixed in a update as it's currently the  number 1 annoyance for us.

**Comment by Cretection** [comment]
Just updated to 1.9.5 and this issue is still there.

Working with:
PHP 5.6
osTicket 1.9.5
Safari and Firefox on Mac

**Comment by Cretection** [comment]
So I tried variation to reconstruct this bug on my System. I get it only with PHP 5.6.x and my personal PHP.ini. Without my personal PHP.ini and with a general PHP.ini it works without problems.
So I start to test the old configuration and now I know "suhosin" is the/my problem.
Activ suhosin with this confs: 
```
[Extensions]
  extension = "suhosin.so"

[Suhosin]
  suhosin.request.max_vars = 400
  suhosin.request.max_varname_length = 200
  suhosin.post.max_name_length = 200
  suhosin.get.max_name_length = 200
  suhosin.post.max_vars = 400
  suhosin.get.max_value_length = 2000
  suhosin.executor.include.whitelist = "phar vfs"
```
does not work and I get this error every time.

**Comment by FrancescoGarofalo** [comment]
i'm new to osticket, it looks like i got the same issue described above.

OS Ticket 1.9.5 

php.ini
cgi.fix_pathinfo=1

my.cnf
character_set_server=utf8
character_set_client=utf8

Webserver apache 2.2
AddDefaultCharset UTF-8



it seems not updating the pages while using non asci chars..


Example:
```sql

&egrave; <-- Works 
è <-- Does not.

```
no error is returned or logged from ajax.

Full trace:

   95 Query	UPDATE contains the correct value      "è"
^ should be the one triggered by Save Change button

  96 Query	UPDATE  seems not, value is become "?"

^ should be the one triggered by Ajax

```sql
95 Query	SELECT * FROM ost_draft WHERE id=64
		   95 Query	UPDATE ost_draft SET updated=NOW(),body='<div>%{ticket.name}<br /> <br />Grazie per averci contattato.<br />Le risponderemo quanto prima è<br /></div>' WHERE id=64
		   95 Query	REPLACE INTO ost_session SET session_updated=NOW() ,session_id='1b9ce6863cb5f9fa846159af3cf7997e',session_data=,session_expire=(NOW() + INTERVAL 86400 SECOND),user_id=1,user_ip='172.16.23.2',user_agent='Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:35.0) Gecko/20100101 Firefox/35.0'
		   95 Quit	
150109 20:20:04	   96 Connect	ticket@localhost on 
		   96 Query	SET NAMES "utf8"
		   96 Query	SET CHARACTER SET "utf8"
		   96 Query	SET COLLATION_CONNECTION=utf8_general_ci
		   96 Query	SET NAMES utf8
		   96 Query	SET SESSION sql_mode=''
		   96 Query	set autocommit=1
		   96 Init DB	osticket
		   96 Query	SELECT `ostversion` FROM ost_config WHERE id=1
		   96 Query	SELECT session_data FROM ost_session WHERE session_id='1b9ce6863cb5f9fa846159af3cf7997e'  AND session_expire>NOW()
		   96 Query	SELECT id, `key`, value, `updated` FROM ost_config WHERE `namespace` = 'core'
		   96 Query	SELECT * FROM ost_plugin
		   96 Query	SELECT staff.created as added, grp.*, staff.*  FROM ost_staff staff  LEFT JOIN ost_groups grp ON(grp.group_id=staff.group_id)
               WHERE username='francesco'
		   96 Query	SELECT id, `key`, value, `updated` FROM ost_config WHERE `namespace` = 'staff.1'
		   96 Query	SELECT * FROM ost_timezone WHERE id=15
		   96 Query	SELECT page.*, count(topic.page_id) as topics  FROM ost_content page  LEFT JOIN ost_help_topic topic ON(topic.page_id=page.id)  WHERE page.content_id=2 GROUP By page.id
		   96 Query	SELECT id FROM ost_content WHERE name='Grazie - Thank You'
		   96 Query	UPDATE ost_content SET  updated=NOW() , `type`='thank-you', name='Grazie - Thank You', body='<div>%{ticket.name}<br /> <br />Grazie per averci contattato.<br />Le risponderemo quanto prima ?<br /></div>', isactive=1, notes='This template defines the content displayed on the Thank-You page after a Client submits a new ticket in the Client Portal.' WHERE id=2
		   96 Query	SELECT page.*, count(topic.page_id) as topics  FROM ost_content page  LEFT JOIN ost_help_topic topic ON(topic.page_id=page.id)  WHERE page.content_id=2 GROUP By page.id
		   96 Query	DELETE FROM ost_attachment WHERE object_id=2   AND `type`='P' AND inline = 1
		   96 Query	DELETE attach FROM ost_attachment attach
                INNER JOIN ost_draft draft
                ON (attach.object_id = draft.id AND attach.`type`='D')
                WHERE draft.`namespace` LIKE 'page.2'
		   96 Query	DELETE FROM ost_draft WHERE `namespace` LIKE 'page.2'
		   96 Prepare	SELECT `ost_form_entry`.* FROM `ost_form_entry` WHERE `ost_form_entry`.`object_type` = ? ORDER BY `ost_form_entry`.`sort` ASC LIMIT 1
		   96 Execute	SELECT `ost_form_entry`.* FROM `ost_form_entry` WHERE `ost_form_entry`.`object_type` = 'C' ORDER BY `ost_form_entry`.`sort` ASC LIMIT 1
		   96 Close stmt	
		   96 Prepare	SELECT `ost_form_entry_values`.* FROM `ost_form_entry_values` JOIN `ost_form_field` A1 ON (`ost_form_entry_values`.`field_id` = A1.`id`) WHERE `ost_form_entry_values`.`entry_id` = ? ORDER BY A1.`sort` ASC
		   96 Execute	SELECT `ost_form_entry_values`.* FROM `ost_form_entry_values` JOIN `ost_form_field` A1 ON (`ost_form_entry_values`.`field_id` = A1.`id`) WHERE `ost_form_entry_values`.`entry_id` = 2 ORDER BY A1.`sort` ASC
		   96 Close stmt	
		   96 Prepare	SELECT `ost_form_field`.* FROM `ost_form_field` WHERE `ost_form_field`.`id` = ? ORDER BY `ost_form_field`.`sort` ASC LIMIT 1
		   96 Execute	SELECT `ost_form_field`.* FROM `ost_form_field` WHERE `ost_form_field`.`id` = 23 ORDER BY `ost_form_field`.`sort` ASC LIMIT 1
		   96 Close stmt	
		   96 Prepare	SELECT `ost_list`.* FROM `ost_list` ORDER BY `ost_list`.`name` ASC
		   96 Execute	SELECT `ost_list`.* FROM `ost_list` ORDER BY `ost_list`.`name` ASC
		   96 Query	SELECT id, `key`, value, `updated` FROM ost_config WHERE `namespace` = 'list.1'
		   96 Close stmt	
		   96 Query	REPLACE INTO ost_session SET session_updated=NOW() ,session_id='1b9ce6863cb5f9fa846159af3cf7997e',session_data=,session_expire=(NOW() + INTERVAL 86400 SECOND),user_id=1,user_ip='172.16.23.2',user_agent='Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:35.0) Gecko/20100101 Firefox/35.0'
		   96 Quit	
150109 20:20:05	   97 Connect	ticket@localhost on 
		   97 Query	SET NAMES "utf8"
		   97 Query	SET CHARACTER SET "utf8"
		   97 Query	SET COLLATION_CONNECTION=utf8_general_ci
		   97 Query	SET NAMES utf8
		   97 Query	SET SESSION sql_mode=''
		   97 Query	set autocommit=1
		   97 Init DB	osticket
		   97 Query	SELECT `ostversion` FROM ost_config WHERE id=1
		   97 Query	SELECT session_data FROM ost_session WHERE session_id='1b9ce6863cb5f9fa846159af3cf7997e'  AND session_expire>NOW()
		   97 Query	SELECT id, `key`, value, `updated` FROM ost_config WHERE `namespace` = 'core'
		   97 Query	SELECT * FROM ost_plugin
		   97 Query	SELECT staff.created as added, grp.*, staff.*  FROM ost_staff staff  LEFT JOIN ost_groups grp ON(grp.group_id=staff.group_id)
               WHERE username='francesco'
		   97 Query	SELECT id, `key`, value, `updated` FROM ost_config WHERE `namespace` = 'staff.1'
		   97 Query	SELECT * FROM ost_timezone WHERE id=15
		   97 Query	SELECT ticket_id FROM ost_ticket T1  INNER JOIN ost_ticket_status status
                ON (status.id=T1.status_id AND status.state="open")  LEFT JOIN ost_sla T2 ON (T1.sla_id=T2.id AND T2.isactive=1)  WHERE isoverdue=0  AND ((reopened is NULL AND duedate is NULL AND TIME_TO_SEC(TIMEDIFF(NOW(),T1.created))>=T2.grace_period*3600)  OR (reopened is NOT NULL AND duedate is NULL AND TIME_TO_SEC(TIMEDIFF(NOW(),reopened))>=T2.grace_period*3600)  OR (duedate is NOT NULL AND duedate<NOW())  ) ORDER BY T1.created LIMIT 50
		   97 Query	DELETE FROM ost_ticket_lock WHERE expire<NOW()
		   97 Query	SELECT A1.`id`, A1.`title`, A1.`body`, A1.`format` FROM `ost_ticket_thread` A1
            LEFT JOIN `ost__search` A2 ON (A1.`id` = A2.`object_id` AND A2.`object_type`='H')
            WHERE A2.`object_id` IS NULL AND (A1.poster <> 'SYSTEM')
            AND (LENGTH(A1.`title`) + LENGTH(A1.`body`) > 0)
            ORDER BY A1.`id` DESC
		   97 Query	SELECT A1.`ticket_id` FROM `ost_ticket` A1
            LEFT JOIN `ost__search` A2 ON (A1.`ticket_id` = A2.`object_id` AND A2.`object_type`='T')
            WHERE A2.`object_id` IS NULL
            ORDER BY A1.`ticket_id` DESC
		   97 Query	SELECT A1.`id` FROM `ost_user` A1
            LEFT JOIN `ost__search` A2 ON (A1.`id` = A2.`object_id` AND A2.`object_type`='U')
            WHERE A2.`object_id` IS NULL
            ORDER BY A1.`id` DESC
		   97 Query	SELECT A1.`id` FROM `ost_organization` A1
            LEFT JOIN `ost__search` A2 ON (A1.`id` = A2.`object_id` AND A2.`object_type`='O')
            WHERE A2.`object_id` IS NULL
            ORDER BY A1.`id` DESC
		   97 Query	SELECT A1.`faq_id` FROM `ost_faq` A1
            LEFT JOIN `ost__search` A2 ON (A1.`faq_id` = A2.`object_id` AND A2.`object_type`='K')
            WHERE A2.`object_id` IS NULL
            ORDER BY A1.`faq_id` DESC
		   97 Query	REPLACE INTO ost_session SET session_updated=NOW() ,session_id='1b9ce6863cb5f9fa846159af3cf7997e',session_data=,session_expire=(NOW() + INTERVAL 86400 SECOND),user_id='0',user_ip='172.16.23.2',user_agent='Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:35.0) Gecko/20100101 Firefox/35.0'
		   97 Quit	
		   98 Connect	ticket@localhost on 
		   98 Query	SET NAMES "utf8"
		   98 Query	SET CHARACTER SET "utf8"
		   98 Query	SET COLLATION_CONNECTION=utf8_general_ci
		   98 Query	SET NAMES utf8
		   98 Query	SET SESSION sql_mode=''
		   98 Query	set autocommit=1
		   98 Init DB	osticket
		   98 Query	SELECT `ostversion` FROM ost_config WHERE id=1
		   98 Query	SELECT session_data FROM ost_session WHERE session_id='1b9ce6863cb5f9fa846159af3cf7997e'  AND session_expire>NOW()
		   98 Query	SELECT id, `key`, value, `updated` FROM ost_config WHERE `namespace` = 'core'
		   98 Query	SELECT * FROM ost_plugin
		   98 Query	SELECT staff.created as added, grp.*, staff.*  FROM ost_staff staff  LEFT JOIN ost_groups grp ON(grp.group_id=staff.group_id)
               WHERE username='francesco'
		   98 Query	SELECT id, `key`, value, `updated` FROM ost_config WHERE `namespace` = 'staff.1'
		   98 Query	SELECT * FROM ost_timezone WHERE id=15
		   98 Quit	
		   99 Connect	ticket@localhost on 
		   99 Query	SET NAMES "utf8"
		   99 Query	SET CHARACTER SET "utf8"
		   99 Query	SET COLLATION_CONNECTION=utf8_general_ci
		   99 Query	SET NAMES utf8
		   99 Query	SET SESSION sql_mode=''
		   99 Query	set autocommit=1
		   99 Init DB	osticket
		   99 Query	SELECT `ostversion` FROM ost_config WHERE id=1
		   99 Query	SELECT session_data FROM ost_session WHERE session_id='1b9ce6863cb5f9fa846159af3cf7997e'  AND session_expire>NOW()
		   99 Query	SELECT id, `key`, value, `updated` FROM ost_config WHERE `namespace` = 'core'
		   99 Query	SELECT * FROM ost_plugin
		   99 Query	SELECT staff.created as added, grp.*, staff.*  FROM ost_staff staff  LEFT JOIN ost_groups grp ON(grp.group_id=staff.group_id)
               WHERE username='francesco'
		   99 Query	SELECT id, `key`, value, `updated` FROM ost_config WHERE `namespace` = 'staff.1'
		   99 Query	SELECT * FROM ost_timezone WHERE id=15
		   99 Query	SELECT id FROM ost_draft WHERE `namespace`='page.2' AND staff_id=1
		   99 Quit	
		  100 Connect	ticket@localhost on 
		  100 Query	SET NAMES "utf8"
		  100 Query	SET CHARACTER SET "utf8"
		  100 Query	SET COLLATION_CONNECTION=utf8_general_ci
		  100 Query	SET NAMES utf8
		  100 Query	SET SESSION sql_mode=''
		  100 Query	set autocommit=1
		  100 Init DB	osticket
		  100 Query	SELECT `ostversion` FROM ost_config WHERE id=1
		  100 Query	SELECT session_data FROM ost_session WHERE session_id='1b9ce6863cb5f9fa846159af3cf7997e'  AND session_expire>NOW()
		  100 Query	SELECT id, `key`, value, `updated` FROM ost_config WHERE `namespace` = 'core'
		  100 Query	SELECT * FROM ost_plugin
150109 20:20:06	  100 Query	SELECT staff.created as added, grp.*, staff.*  FROM ost_staff staff  LEFT JOIN ost_groups grp ON(grp.group_id=staff.group_id)
               WHERE username='francesco'
		  100 Query	SELECT id, `key`, value, `updated` FROM ost_config WHERE `namespace` = 'staff.1'
		  100 Query	SELECT * FROM ost_timezone WHERE id=15
		  100 Query	SELECT page.*, count(topic.page_id) as topics  FROM ost_content page  LEFT JOIN ost_help_topic topic ON(topic.page_id=page.id)  WHERE page.content_id=2 GROUP By page.id
		  100 Prepare	SELECT `ost_form_entry`.* FROM `ost_form_entry` WHERE `ost_form_entry`.`object_type` = ? ORDER BY `ost_form_entry`.`sort` ASC LIMIT 1
		  100 Execute	SELECT `ost_form_entry`.* FROM `ost_form_entry` WHERE `ost_form_entry`.`object_type` = 'C' ORDER BY `ost_form_entry`.`sort` ASC LIMIT 1
		  100 Close stmt	
		  100 Prepare	SELECT `ost_form_entry_values`.* FROM `ost_form_entry_values` JOIN `ost_form_field` A1 ON (`ost_form_entry_values`.`field_id` = A1.`id`) WHERE `ost_form_entry_values`.`entry_id` = ? ORDER BY A1.`sort` ASC
		  100 Execute	SELECT `ost_form_entry_values`.* FROM `ost_form_entry_values` JOIN `ost_form_field` A1 ON (`ost_form_entry_values`.`field_id` = A1.`id`) WHERE `ost_form_entry_values`.`entry_id` = 2 ORDER BY A1.`sort` ASC
		  100 Close stmt	
		  100 Prepare	SELECT `ost_form_field`.* FROM `ost_form_field` WHERE `ost_form_field`.`id` = ? ORDER BY `ost_form_field`.`sort` ASC LIMIT 1
		  100 Execute	SELECT `ost_form_field`.* FROM `ost_form_field` WHERE `ost_form_field`.`id` = 23 ORDER BY `ost_form_field`.`sort` ASC LIMIT 1
		  100 Close stmt	
		  100 Prepare	SELECT `ost_list`.* FROM `ost_list` ORDER BY `ost_list`.`name` ASC
		  100 Execute	SELECT `ost_list`.* FROM `ost_list` ORDER BY `ost_list`.`name` ASC
		  100 Query	SELECT id, `key`, value, `updated` FROM ost_config WHERE `namespace` = 'list.1'
		  100 Close stmt	
		  100 Query	REPLACE INTO ost_session SET session_updated=NOW() ,session_id='1b9ce6863cb5f9fa846159af3cf7997e',session_data=,session_expire=(NOW() + INTERVAL 86400 SECOND),user_id=1,user_ip='172.16.23.2',user_agent='Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:35.0) Gecko/20100101 Firefox/35.0'
		  100 Quit	
		  101 Connect	ticket@localhost on 
		  101 Query	SET NAMES "utf8"
		  101 Query	SET CHARACTER SET "utf8"
		  101 Query	SET COLLATION_CONNECTION=utf8_general_ci
		  101 Query	SET NAMES utf8
		  101 Query	SET SESSION sql_mode=''
		  101 Query	set autocommit=1
		  101 Init DB	osticket
		  101 Query	SELECT `ostversion` FROM ost_config WHERE id=1
		  101 Query	SELECT session_data FROM ost_session WHERE session_id='1b9ce6863cb5f9fa846159af3cf7997e'  AND session_expire>NOW()
		  101 Query	SELECT id, `key`, value, `updated` FROM ost_config WHERE `namespace` = 'core'
		  101 Query	SELECT * FROM ost_plugin
		  101 Query	SELECT staff.created as added, grp.*, staff.*  FROM ost_staff staff  LEFT JOIN ost_groups grp ON(grp.group_id=staff.group_id)
               WHERE username='francesco'
		  101 Query	SELECT id, `key`, value, `updated` FROM ost_config WHERE `namespace` = 'staff.1'
		  101 Query	SELECT * FROM ost_timezone WHERE id=15
		  101 Quit	
150109 20:20:15	  102 Connect	ticket@localhost on 
		  102 Query	SET NAMES "utf8"
		  102 Query	SET CHARACTER SET "utf8"
		  102 Query	SET COLLATION_CONNECTION=utf8_general_ci
		  102 Query	SET NAMES utf8
		  102 Query	SET SESSION sql_mode=''
		  102 Query	set autocommit=1
		  102 Init DB	osticket
		  102 Query	SELECT `ostversion` FROM ost_config WHERE id=1
		  102 Query	SELECT session_data FROM ost_session WHERE session_id='1b9ce6863cb5f9fa846159af3cf7997e'  AND session_expire>NOW()
		  102 Query	SELECT id, `key`, value, `updated` FROM ost_config WHERE `namespace` = 'core'
		  102 Query	SELECT * FROM ost_plugin
		  102 Query	SELECT staff.created as added, grp.*, staff.*  FROM ost_staff staff  LEFT JOIN ost_groups grp ON(grp.group_id=staff.group_id)
               WHERE username='francesco'
		  102 Query	SELECT id, `key`, value, `updated` FROM ost_config WHERE `namespace` = 'staff.1'
		  102 Query	SELECT * FROM ost_timezone WHERE id=15
		  102 Query	INSERT INTO ost_draft SET `namespace`='page.2' ,body='<div>%{ticket.name}<br /> <br />Grazie per averci contattato.<br />Le risponderemo quanto prima</div>' ,staff_id=1 ,created=NOW()
		  102 Query	SELECT * FROM ost_draft WHERE id=65
		  102 Query	REPLACE INTO ost_session SET session_updated=NOW() ,session_id='1b9ce6863cb5f9fa846159af3cf7997e',session_data=,session_expire=(NOW() + INTERVAL 86400 SECOND),user_id=1,user_ip='172.16.23.2',user_agent='Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:35.0) Gecko/20100101 Firefox/35.0'
		  102 Quit	
150109 20:21:01	  103 Connect	ticket@localhost on 
		  103 Query	SET NAMES "utf8"
		  103 Query	SET CHARACTER SET "utf8"
		  103 Query	SET COLLATION_CONNECTION=utf8_general_ci
		  103 Query	SET NAMES utf8
		  103 Query	SET SESSION sql_mode=''
		  103 Query	set autocommit=1
		  103 Init DB	osticket
		  103 Query	SELECT `ostversion` FROM ost_config WHERE id=1
		  103 Query	SELECT session_data FROM ost_session WHERE session_id='7bd346c5802d4178342d944ff494bd44'  AND session_expire>NOW()
		  103 Query	SELECT id, `key`, value, `updated` FROM ost_config WHERE `namespace` = 'core'
		  103 Query	SELECT * FROM ost_timezone WHERE id=15
		  103 Query	SELECT * FROM ost_plugin
		  103 Query	SELECT email_id, mail_errors FROM ost_email WHERE mail_active=1   AND (mail_errors<=5 OR (TIME_TO_SEC(TIMEDIFF(NOW(), mail_lasterror))>600) )  AND (mail_lastfetch IS NULL OR TIME_TO_SEC(TIMEDIFF(NOW(), mail_lastfetch))>mail_fetchfreq*60) ORDER BY mail_lastfetch ASC
		  103 Query	SELECT ticket_id FROM ost_ticket T1  INNER JOIN ost_ticket_status status
                ON (status.id=T1.status_id AND status.state="open")  LEFT JOIN ost_sla T2 ON (T1.sla_id=T2.id AND T2.isactive=1)  WHERE isoverdue=0  AND ((reopened is NULL AND duedate is NULL AND TIME_TO_SEC(TIMEDIFF(NOW(),T1.created))>=T2.grace_period*3600)  OR (reopened is NOT NULL AND duedate is NULL AND TIME_TO_SEC(TIMEDIFF(NOW(),reopened))>=T2.grace_period*3600)  OR (duedate is NOT NULL AND duedate<NOW())  ) ORDER BY T1.created LIMIT 50
		  103 Query	DELETE FROM ost_ticket_lock WHERE expire<NOW()
		  103 Query	DELETE FROM ost_draft WHERE `namespace` LIKE 'ticket.client.%'
            AND ((updated IS NULL AND datediff(now(), created) > 14)
                OR datediff(now(), updated) > 14)
		  103 Query	SELECT A1.`id`, A1.`title`, A1.`body`, A1.`format` FROM `ost_ticket_thread` A1
            LEFT JOIN `ost__search` A2 ON (A1.`id` = A2.`object_id` AND A2.`object_type`='H')
            WHERE A2.`object_id` IS NULL AND (A1.poster <> 'SYSTEM')
            AND (LENGTH(A1.`title`) + LENGTH(A1.`body`) > 0)
            ORDER BY A1.`id` DESC
		  103 Query	SELECT A1.`ticket_id` FROM `ost_ticket` A1
            LEFT JOIN `ost__search` A2 ON (A1.`ticket_id` = A2.`object_id` AND A2.`object_type`='T')
            WHERE A2.`object_id` IS NULL
            ORDER BY A1.`ticket_id` DESC
		  103 Query	SELECT A1.`id` FROM `ost_user` A1
            LEFT JOIN `ost__search` A2 ON (A1.`id` = A2.`object_id` AND A2.`object_type`='U')
            WHERE A2.`object_id` IS NULL
            ORDER BY A1.`id` DESC
		  103 Query	SELECT A1.`id` FROM `ost_organization` A1
            LEFT JOIN `ost__search` A2 ON (A1.`id` = A2.`object_id` AND A2.`object_type`='O')
            WHERE A2.`object_id` IS NULL
            ORDER BY A1.`id` DESC
		  103 Query	SELECT A1.`faq_id` FROM `ost_faq` A1
            LEFT JOIN `ost__search` A2 ON (A1.`faq_id` = A2.`object_id` AND A2.`object_type`='K')
            WHERE A2.`object_id` IS NULL
            ORDER BY A1.`faq_id` DESC
		  103 Quit	
```

**Comment by stooz** [comment]
I have found a bug in js/redactor-osticket.js

**Comment by ntozier** [comment]
@stooz are you going to expand on what that bug is?

**Comment by stooz** [comment]
Sorry, I have updated my comment, i pressed enter and it posted before I was ready :)

**Comment by greezybacon** [comment]
@stooz You should be able to see in the Chrome network view that something like `POST ajax.php/draft/11` was sent to the server, not `ajax.php.draft...`

**Comment by cgubi** [comment]
So the fix suggested by stooz is not valid?

**Comment by greezybacon** [comment]
@cgubi @stooz I think the fix "works" because it causes the if statement to always fail and not display the error.

**Comment by cgubi** [comment]
Got it. Do you think that a "real" fix will come sooner or later?

**Comment by greezybacon** [comment]
@cgubi the draft system was completely rewritten in `develop-next`. I truly hope this issue will die

**Comment by Hannibal226** [comment]
After thinking it was gone in new release 1.9.6 today it sadly appeared again.
It was after saving changes in ticket and first chrome asked like often "do u want to leave this page" after that I got a second info message "unable to safe draft....."

So just to let u know that it seems to be still there.

**Comment by greezybacon** [comment]
Yeah, I meant the draft system is rewritten in the `develop-next` branch (yet unreleased)

**Comment by Hannibal226** [comment]
@greezybacon 
Haha sorry, nothing said then :P

**Comment by boosters** [comment]
I am using the latest version and i am getting the same error. I tried chrome and firefox, same issue. Please fix this asap, i can't able to add FAQ.

**Comment by ntozier** [comment]
What does "latest version" mean to you?

**Comment by boosters** [comment]
I mean i recently installed through softaculous from hosting server

**Comment by ntozier** [comment]
So then what version are you running?

**Comment by boosters** [comment]
It has written 1.9.8

**Comment by junosapien** [comment]
I am attempting to integrate 1.9.8 with my website and am getting the same thing (tested on Firefox only).  Firebug reports the following:
TypeError: json is null
redacto... > eval (line 1, col 39172)
...ion(data){var json=$.parseJSON(data);if(typeof json.error=="undefined"){this.cal...

**Comment by dsoden** [comment]
My president has found this and is annoyed because I make everyone file a ticket due to our volume. any idea when this may be fixed. I set a watched on this hoping soon.

clarify this please?
is this the fix?

js/redactor-osticket.js Line 308 ; if (settings.url.indexOf('ajax.php/draft' ....
to 
js/redactor-osticket.js Line 308 ; if (settings.url.indexOf('ajax.draft.php' ....

**Comment by junosapien** [comment]
to dsoden.... I believe the change you mention (ajax.php/draft to ajax.php.draft) will prevent the popup from happening, but it DOES NOT remove the javascript errors that get reported in the console of firebug.

**Comment by greezybacon** [comment]
@dsoden the draft system was rewritten for v1.10 (`develop-next` branch) in hopes of addressing this issue specifically

**Comment by dsoden** [comment]
Thanks so much!



Sent from my Verizon Wireless 4G LTE smartphone


-------- Original message --------

**Comment by junosapien** [comment]
Any idea when v1.10 will be available with this fix?

FWIW: Chrome reports this error:

**Comment by junosapien** [comment]
Uncaught TypeError: Cannot read property 'error' of null(anonymous function) @ VM124:1v.extend.proxy.v.isFunction.s @ jquery-1.8.3.min.js?9c6acce:2v.Callbacks.l @ jquery-1.8.3.min.js?9c6acce:2v.Callbacks.c.fireWith @ jquery-1.8.3.min.js?9c6acce:2T @ jquery-1.8.3.min.js?9c6acce:2v.support.ajax.v.ajaxTransport.send.r @ jquery-1.8.3.min.js?9c6acce:2

**Comment by barrydegraaff** [comment]
https://github.com/osTicket/osTicket-1.8/pull/2480

**Comment by empugandring** [comment]
try edit file scp/js/ticket.js
find code :
     if(e.type=='submit') { //Submit. double check!
             //remove nav away warning if any.
             $(window).unbind('beforeunload');

and add code :
      $(document).unbind('pjax:beforeSend.changed');

it's work for me.

**Comment by Hannibal226** [comment]
As it seems like my last post wasn't published, I'll do it again:

After moving our ticket system from my local PC to our webserver we now get a lot more of those "unable to save draft" alerts. (v 1.9.12)
So I think it's because the answer time etc.

But my main question now is:
Is there now any feedback, that it's gone with the <develop-next>? I remember that even some reported this bug with 1.10 (couldn't find now)

Just asking because it's really annoying to see multiple replies or opening of tickets.

CHEERS!

**Comment by dmiguel92** [comment]
I have this problem at 1.9.12. How can I solve it?

**Comment by Hannibal226** [comment]
@greezybacon 

Sorry for bothering again, but may u could clearify the actual stand o things here?

U always said <code>develop-next</code> but is this already include in actual RCs then?
I remember that some ppl mentioned it wasn't better in first RC, too.

And if there is a actual working version, is there any plan for RC3 or next is final?
Should we just wait then for production usage?
[1.9.12 is cool, but we need the fix and custom queues in ticket list :P ]

Thanks for all ur work and support!
CHEERS

**Comment by ntozier** [comment]
Q: U always said develop-next but is this already include in actual RCs then?
A: @greezybacon said "the draft system was rewritten for v1.10 (develop-next branch)" on May 28th.
This is after 1.10DPR was released.
1.10RC1 was released on July 22nd.
1.10RC2 was released on August 19th.
So the new draft system would be in all of those versions.

Q: And if there is a actual working version, is there any plan for RC3 or next is final?
A: Develop-next is whatever the next version will be when its labelled and packed for release.  Be it 1.10rc3 or 1.10ST or 1.10.0.

Q: Should we just wait then for production usage?
A: I never recommend running DPRs or RCs in production.

**Comment by mfelber** [comment]
My understanding is that the custom queue feature will not be part of osticket 1.10. It will be part of the next major version: https://github.com/osTicket/osTicket-1.8/pull/2577#issuecomment-146565406

**Comment by Hannibal226** [comment]
@ntozier
Thanks for reply

1) OK so this should be fixed in RCs and I read feedback to DPR, maybe. 

2) But this isn't what I mean. The devs should have a bin of things to do and I think they know when a new RC is necessary or final. So there's a difference for me, when I know the work is going ahead for the final or the next RC3 first. 

3) In general yes, but it's always a question of features and stability. So that's why I asked 2)


@mfelber 
Thanks for the info! 
U know what "major version" will looks like then? Because I thought 1.10 should be one. 

CHEERS

**Comment by mfelber** [comment]
@Hannibal226 
Yes 1.10 is a major release (but without custom queues). I don't know how the next major release (with custom queues) after 1.10 will be named or how it will looks like. There isn't much information on this..

**Comment by Hannibal226** [comment]
@mfelber

Alright thanks again ;)

mfelber <notifications@github.com> schrieb am Sa., 9. Jan. 2016, 12:29:

**Comment by schlos** [comment]
Reproducible in 1.9.12.

#2309 is duplicate of this issue (reported for v1.9.11)

**Comment by adpe** [comment]
Dear @JediKev 

This problem still occurs when answering a ticket in the end-user view. The `textarea` causing this error is in this file `include/client/view.inc.php`.

Can you please reopen this ticket or should I create a new one?

Greets
Adrian
