### ISSUE TITLE
Bug 1.9.8: checkbox loose their state when an agent edits the ticket

### ISSUE THREAD

**Issue by markus4000** [osTicket/osTicket#2116]
when an agent edits the ticket, all the checkboxes loose ther state and are disabled.

**Comment by mfelber** [comment]
I can confirm this issue. A activated checkbox which was successfully saved, is shown unchecked when you edit the ticket.

**Comment by mfelber** [comment]
v. 1.9.7 and 1.9.8.1 does have this issue too, v.1.10 is not affected.

**Comment by infectormp** [comment]
@mfelber this was fixed in 1.9.7 #1866

**Comment by mfelber** [comment]
@infectormp I can see that the changes from #1866 are in the code. But the issue nevertheless occurs in the versions I have mentioned (fresh installs). 
This is my way to reproduce it:
1) I add a checkbox to the ticket form and save it.
2) I create a ticket, activate the checkbox and save the ticket.
3) Then I edit the ticket and the checkbox is shown as not activated.

**Comment by Orthodyne-mve** [comment]
I found the issue, see pull request #2928 
Actually one function would return False instead of null, so it was interpreted as the value for the checkbox...

**Comment by dougeth** [comment]
I can confirm the bug still exists despite the code adjustment form  [#1866](https://github.com/osTicket/osTicket/pull/1866).  

**System Info**
osTicket Version 	v1.9.14 (8b927a0) — Up to date
Web Server Software 	Apache/2.2.15 (CentOS)
MySQL Version 	5.1.73
PHP Version 	5.3.3

**Code from class.forms.php (with line numbers)**
2016     function getValue() {
   2017         $data = $this->field->getSource();
   2018         if (count($data)) {
   2019             if (!isset($data[$this->name]))
   2020                 return false;
   2021             return @in_array($this->field->get('id'), $data[$this->name]);
   2022         }
   2023         return parent::getValue();
   2024     }

**Comment by dougeth** [comment]
Nevermind.  I see the additional code fix from @Orthodyne-mve .  Why hasn't this been included in the the latest releases?

   2016     function getValue() {
   2017         $data = $this->field->getSource();
   2018         if (count($data)) {
   2019             if (!isset($data[$this->name]) **&& ($_SERVER['REQUEST_METHOD'] == 'POST'))**
   2020                 return false;
   2021             return @in_array($this->field->get('id'), $data[$this->name]);
   2022         }
   2023         return parent::getValue();
