### ISSUE TITLE
Lack of Possibility to put Ticket back into main cue (UnAssign)

### ISSUE THREAD

**Issue by konqui** [osTicket/osTicket#3308]
It would be really helpfull to have the possibillity to unassign a ticket.

**Comment by wfoster** [comment]
Could you give an example of why you would ever need this?

**Comment by wfoster** [comment]
Your comment may be misleading because the title of this issue is to put a ticket back into the main cue.
Do you want to have assigned tickets show on the open tickets view? you can do this via the admin console. Log in as admin user go to Admin Panel -> Settings -> Tickets
Make sure that the last two options are not selected. This would keep your assigned and or answered tickets on the open (main) view
![image](https://cloud.githubusercontent.com/assets/7644638/18221724/10788df8-7183-11e6-9b68-4e89fc5fc363.png)

**Comment by konqui** [comment]
No i wanna have a possibillity to make them unassigned again. Problem is a the Following, when i close a ticket go to Vacation and then the Customer answer my Last Message from TicketSystem.

The Ticket gets automatically reopend which is good but it is still asigned to me. Altought it may be a total new Case and not anyhow related to the previous Issue. So it also could be handled by anyone else than me. But Nobody will recognize it or do anything sinze it is already asigned to me.

2nd Scenario may be that i claimed the wrong ticket by mistake and wanna put it back to the main queue / unassigne it.

So there should be 1st a Button to push Tickets manually back to the main queue. And also Tickets which get reopend due to Answers by Mail should be reopend as assigned to Nobody.

I hope now you can understand better what i wanna have. Its not a Bug but a Missing Feature i really wanna have.




Gruss Konqui

konqui.kubuntu@gmail.com
--------------------------------------------
Bug fixed it! - anders gesagt, ich hab den DAU erschlagen!!

**Comment by wfoster** [comment]
One way to solve the reopening a ticket problem is to go Admin panel -> Manage -> Lists -> Ticket Statuses -> click on closed -> Properties tab and deselect "Allow tickets on this status to be reopened by end users"
![image](https://cloud.githubusercontent.com/assets/7644638/18224145/a758ea1c-71cc-11e6-9047-9e8f28f2d474.png)

We have a canned response asking that the user confirm the issue is resolved and that we can now close the ticket. If they then reply on a closed ticket I believe it opens a new ticket for them which would be unassigned but will have the old ticket number in the subject as a reference to fall back onto to see the original issue with a new ticket number.

Your 2nd scenario would probably be best solved with departments or teams depending on how you have the system configured. A department/Team should be able to see the ticket assigned to the dept/team even though you have claimed it. So if somebody in your department should have the ticket instead of you then simply do a transfer to that agent. I am sure you guys talk to each other right. If the ticket belongs to another department then assign it to them and post an internal note asking that somebody to have a look at it.

Are you an internal department servicing internal clients or are you an online help desk for a consumer?

**Comment by wfoster** [comment]
Your 2nd scenario is exactly why we use teams in our OST environment. If one of us are away then the other agents in your team can fulfill the ticket. Departments can be used in the same way if set up correctly.
How lazy must I be knowing that you have gone on holiday and I simply ignore your tickets. Obvious to this is that you have assigned tickets show on the open view.
Sounds like you have to maybe tweak your configuration a little bit to suit your environment a bit better rather than looking at system additions.
Are you set up to auto assign tickets when you open them or have you got filters that auto assign to agents?

**Comment by konqui** [comment]
No, we have no auto assign. Tickets are only manually assigned or claimed. Due to the amount of tickets we get, we have two Guys which are just there to assign new incomming Tickets to the right Group/Department. So to make there Life a little easier we have disabled the show assigned tickets in the open queue since there is already some one working on it so they don't need to have a look into it.

Shure i don't know 100% of all the Settings. So Thanks for your informations.

Actually we are still using the old v1.7.0 Version so i didn't understand what you were talking about Teams. Since we have already talked about switching to a newer Version internally i just got the newest Version on my local PC for testing. Now i see what you mean with Teams. And yes you're right i think this will solve the Problem. With the Vaccation thing.

So i will wait until we switched to the new Version and then check if the Workflow i have currently in Mind works as i expect it or not.

But a unasign button will still be usefull just in case i claimed a ticket by mistake and i'm to lazy to 0delete and recreate it.

I can tell you i'm always to lazy to work and looking for Simpler Ways to do my Stuff easier - must be kinda Programmer/SysAdmin-Sickness ;-)

**Comment by ntozier** [comment]
@konqui You do realize that 1.7 isn't supported anymore, right?
With a version that old you could probably pretty easily add an unassign button. 
Assignments are in the ost_ticket table. Look up the ticket and alter the staff_id field for that entry (set it to 0).

**Comment by konqui** [comment]
@ntozier Thats true, i already thought about this. But i don't like local changes since they can be as well documented as possible, but still get lost if the Person who did the changes leaves the Company.

So no it won't be a real Option.

And to prevent the next Idea: As the reactions in this chat show it pretty sure won't get merged into the Main Repo if i commit the changes upstream.

So i think this Feature Request can be closed as it Looks like i will stay the only one who would like to have such a Button.

**Comment by ntozier** [comment]
I was of the opinion that the ability to unassign a ticket was something that was a forth coming feature based on conversations here and at the forums... but you are correct it will never be added as a feature to the 1.7 branch.

**Comment by cardo540** [comment]
Our technicians rotate to different districts every two weeks. When leaving a district, it's handy to be able to unassign myself from a ticket if I had not been able to find the solution during my two weeks in that district, so the next tech can pick it up. Due to the way the company has us rotating, it isn't feasible to use teams or groups. 

It would just be so much handier if the option could be added to allow technicians to unassign themselves. If it is something they abuse, then managers should deal with that.
