### ISSUE TITLE
tickets.json file not found / url not supported

### ISSUE THREAD

**Issue by dikkedimi** [osTicket/osTicket#4148]
### Prerequisites

* [v ] Can you reproduce the problem in a fresh installation of the "develop" branch?
yes
* [v ] Do you have any errors in the PHP error log, or javascript console?
`[proxy_fcgi:error] [pid 15262] [client ###.###.###.###:64265] AH01071: Got error 'Primary script unknown\n'`
* [v ] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [v ] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

cannot access tickets.json file

### Steps to Reproduce

1. open `http://www.help-desk.tld/office/api/http.php/tickets.json` in browser
2. says url not supported.
3. open `http://www.help-desk.tld/office/api/tickets.json` in browser
2. says file not found.
**Expected behavior:** [What you expected to happen]
I'd expect JSON to appear in the browser
**Actual behavior:** [What actually happened]

for `http://www.help-desk.tld/office/api/http.php/tickets.json`:
```
Warning: Declaration of AssignmentForm::render($options) should be compatible with Form::render($staff = true, $title = false, $options = Array) in /home/admin/domains/help-desk.tld/public_html/office/include/class.forms.php on line 4367

Warning: Declaration of TransferForm::render($options) should be compatible with Form::render($staff = true, $title = false, $options = Array) in /home/admin/domains/help-desk.tld/public_html/office/include/class.forms.php on line 4487
URL not supported
```

for the other it doesn't print any PHP errors.
### Versions

Admin panel -> Dashboard -> Information which also additionally gives you information about you server.
```
Serverinfo
--
osTicket versie | v1.10.1 (9ae093d) —  Bij de tijd
Web Server Software | Apache/2
MySQLversie | 5.6.26
PHPversie | 7.0.14

gdlib | Ten behoeve van afbeeldingsbewerking en PDFprinten
imap | Ten behoeve van emailontvangst
xml | XML API
xml-dom | Ten behoeve van emailverwerking
json | Bevordert de prestaties bij het creeren en verwerken van JSON
mbstring | Hoogst aanbevolen bij niet westeuropese taalinhoud
phar | Hoogst aanbevolen voor plugins en taalpakketten
intl | Hoogst aanbevolen bij niet westeuropese taalinhoud
fileinfo | wordt gebruikt om bestandstypen van uploads te detecteren
APCu | Verbetert de algehele prestaties
Zend Opcache | Verbetert de algehele prestaties

cgi.fix_pathinfo | "1" is aanbevolen als AJAX niet werkt
date.timezone | Europe/Amsterdam
```

happens in all browsers.

**Comment by dikkedimi** [comment]
I'm asking because I'm using wordpress to put in tickets. this is now not an option.

**Comment by dikkedimi** [comment]
@greezybacon @protich you seem to know more about the file mentioned in the errors

**Comment by JediKev** [comment]
```
Warning: Declaration of AssignmentForm::render($options) should be compatible with Form::render($staff = true, $title = false, $options = Array) in /home/admin/domains/help-desk.tld/public_html/office/include/class.forms.php on line 4367

Warning: Declaration of TransferForm::render($options) should be compatible with Form::render($staff = true, $title = false, $options = Array) in /home/admin/domains/help-desk.tld/public_html/office/include/class.forms.php on line 4487
URL not supported
```
These errors are due to your PHP version. PHP 7.x+ isn't _fully_ supported yet so you might see these issues. In order to get around these errors try this pull request: https://github.com/osTicket/osTicket/pull/3349

Cheers.

**Comment by deon42** [comment]
Did you get it to work @dikkedimi? In my v1.10 there is no tickets.json file in the api folder. I have been looking via Google for a way to auto create tickets, but found just old info that do not work with v 1.10

**Comment by jesusaristigueta** [comment]
I'm having the same issues with this URL, Using PHP version 5.6.30-0+deb8u1. I need to force it with http.php, but really need it with out that, just http://url.domain.com/api/tickets.json Enabled mod_rewrite, added the settings in Apache's config, but nothing.

**Comment by JediKev** [comment]
`tickets.json` is not a file....the `api/.htaccess` file should rewrite the URL and direct it to `api/http.php` which then sends a signal to create the Ticket or Task in the provided format (in your case JSON). If you are having issues with this then you are most likely having issues with URL Rewriting. If you URL Rewriting is working but it's still not creating tickets then please provide the PHP errors it throws. If you are not getting PHP errors then most likely your URL Rewriting isn't working.

Cheers.

**Comment by jesusaristigueta** [comment]
Exactly, It looks like URL Rewriting issues, but the module is enabled and the .htaccess is set as it should. The Apache configs are looking as they should as well. Not sure of what's wrong.

**Comment by jesusaristigueta** [comment]
Fixed it! It was Apache config issues after all :D

**Comment by jesusaristigueta** [comment]
/etc/apache2/apache2.conf:
<Directory /var/www/>
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
</Directory>
and /etc/apache2/sites-available/000-default.conf:
<Directory "/var/www/html">
          AllowOverride All
</Directory>
Apache2 in Debian 9 😄

**Comment by brightsunlight** [comment]
Hi

Mr jesusaristigueta ,

I am having the same issue but with nginx instead of Apache. How do I do the same thing with nginx?

**Comment by ericmpereira02** [comment]
I am having trouble too, but I am not using Apache I am using windows IIS.
Is there a way to solve this in IIS?

**Comment by discon-nected** [comment]
I tried jesusaristigueta's solution but still have this issue when trying to connect to `.../api/http.php/tickets.json`:
`URL not supported`

Also tried [this tutorial](https://www.digitalocean.com/community/tutorials/how-to-rewrite-urls-with-mod_rewrite-for-apache-on-ubuntu-18-04) for `mod_rewrite`
No issues prior to changing servers.

**Comment by discon-nected** [comment]
Looks like my issue is different:
```
API Error (401)
Valid API key required
```
However the API key is the same I used before, from the same server. Creating a new one did not resolve the error.

**Comment by JediKev** [comment]
@discon-nected 

For the `URL not supported` error, try removing `http.php` from the URL; basically, make the URL like so `.../api/tickets.json`.

As for the `Valid API key required` error set your Default Log Level to DEBUG and then retry the API call. If you get an error again you'll see the API call in the System Logs. Here you will see what IP address made the call and you should create an API key for that specific IP address. Once you do this you should be able to pass the key as a param like `X-API-Key: <API-KEY>`. After this you should be able to create Tickets/Tasks without issues.

Cheers.

**Comment by discon-nected** [comment]
@JediKev Thanks for the reply. The `URL not supported` evidently doesn't mean my message was not routed correctly. If I disable API key validation, the tickets are created normally. I posted more details of my issue in the forums: [https://forum.osticket.com/d/93805-error-in-v1-11-valid-api-key-required](https://forum.osticket.com/d/93805-error-in-v1-11-valid-api-key-required)

The sending IP address matches the IP shown in the error logs. This worked fine on my other server before migrating and upgrading to v1.11. I am using the same DB so all the settings were transferred to the new server. I do use `key` instead of `X-API-Key`, could that make a difference between v1.10 and v1.11?...
![Selection_351](https://user-images.githubusercontent.com/20234985/55576254-5b84ea80-576d-11e9-9d42-dbbc3d5d9160.jpg)

**Comment by JediKev** [comment]
@discon-nected 

Do you have the API Key's `Status` set to `Active` and do you have the options `Can Create Tickets (XML/JSON/EMAIL)` and `Can Execute Cron` Enabled?

Cheers.

**Comment by discon-nected** [comment]
I have all of those except `Can Execute Cron` which I did not enable in the previous installation either.

**Comment by JediKev** [comment]
@discon-nected 

You're going to have to do some `var_dump()`ing to see why it's not recognizing the API Key and/or IP address. You can start here:
https://github.com/osTicket/osTicket/blob/develop/include/api.tickets.php#L99-L100

Dump both `$this->requireApiKey()` and `$this->requireApiKey()->canCreateTickets()` above the `if()` statement and see which one is failing (if any). If one is failing lookup that function and see where it breaks. This will lead you to the root of the issue.

Cheers.
