### ISSUE TITLE
User search not working anymore

### ISSUE THREAD

**Issue by vollkommenIrrelevant** [osTicket/osTicket#4811]
since a few updates in past the user search isn't working anymore. With 1.10.4 we found out that there is a problem with the ajax which handles the search. 1.10.5 didn't repair the function...

To reproduce:
- Tickets->new ticket
- try to enter a username or a E-Mail. 

I marked the interesting parts in the screenshots. Someone having Ideas to solve the problem?

![search](https://user-images.githubusercontent.com/25504254/54741871-03bc8000-4bc0-11e9-882c-d552cb50261f.JPG)
![ajax](https://user-images.githubusercontent.com/25504254/54741874-061eda00-4bc0-11e9-8f3d-53a50038c3b9.png)

**Comment by ntozier** [comment]
1.10.5... Did you check the current version 1.11.0?
Or the tip of development?

**Comment by vollkommenIrrelevant** [comment]
- No, actual I don't want to upgrade to branch 1.11 
-1.10.5 is the tip pf development, isn't it?

**Comment by JediKev** [comment]
@vollkommenIrrelevant 

>1.10.5 is the tip pf development, isn't it?

It's the tip of the 1.10.x series. Now that v1.11 has been released, this is now the tip of development.

>No, actual I don't want to upgrade to branch 1.11

It's a great release with many new features, you should at least try it.

I am not able to reproduce this issue with v1.10.5 and PHP 5.6. Are you running NGINX by chance? (I can't tell as you did not fill out the issue report properly, but I digress)

Cheers.

**Comment by vollkommenIrrelevant** [comment]
> 
> 
> @vollkommenIrrelevant
> 
> > 1.10.5 is the tip pf development, isn't it?
> 
> It's the tip of the 1.10.x series. Now that v1.11 has been released, this is now the tip of development.
> 
> > No, actual I don't want to upgrade to branch 1.11
> 
> It's a great release with many new features, you should at least try it.
Sure, there are a lot of exciting new features. Unfortunately there are some heavy bugreports, so I have to wait before upgrade.

> 
> I am not able to reproduce this issue with v1.10.5 and PHP 5.6. Are you running NGINX by chance? (I can't tell as you did not fill out the issue report properly, but I digress)
nope, Apache 2.4.12 

> 
> Cheers.

**Comment by JediKev** [comment]
@vollkommenIrrelevant 

Yea, I'm using Apache as well and cannot reproduce.

What are the errors you receive in your Apache/PHP error logs? Make sure you have error logging enabled and pointing to a valid file.

Cheers.

**Comment by vollkommenIrrelevant** [comment]
`[21-Mar-2019 15:19:04 UTC] PHP Fatal error:  Access level to Net_LDAP2_RootDSE::__construct() must be public (as in class PEAR) in phar://D:/Websites/....../osticket/include/plugins/auth-ldap.phar/include/Net/LDAP2/RootDSE.php on line 238
`

**Comment by JediKev** [comment]
@vollkommenIrrelevant 

This is why it's important to fill out the entire issue report as LDAP would've been a good thing to know right off the bat instead of me testing without all your exact steps/setup.

Please provide all the appropriate information to reproduce this issue and someone will try to replicate and address the issue. The requested information includes a screenshot of `Admin Panel > Dashboard > Information` tab, a list of installed/enabled plugins, any modifications/third party extensions/themes/etc., and the exact steps to reproduce the issue.

Cheers.

**Comment by vollkommenIrrelevant** [comment]
Well - the plugin isn't in use and nothing is configured. But after deactivation everything works fine.

**Comment by Hoimar** [comment]
I'm also affected by this bug: When the LDAP plugin is enabled, the user search when creating a ticket doesn't work anymore, regardless of whether the plugin is configured or not. When disabling the LDAP plugin it works. This seems to affect versions from 1.8 all they way up to 1.14.1.

This was already brought up [here](https://forum.osticket.com/d/88968-search-users-when-ldap-plugin-is-enabled) and [here](https://github.com/osTicket/osTicket/issues/4418) (same symptoms at least).

Browser error log:
`GET http://localhost/scp/ajax.php/users?q=support 500 (Internal Server Error)`

**Comment by JediKev** [comment]
@Hoimar 

Please post your environment details as well as any related errors from your Apache/IIS error logs, PHP error logs, and AD logs (Note: Error 500 is of no help as it's just a generic server error). Once we get this information we can better assist you. I would assume that something with your LDAP credentials in osTicket are not correct causing the system to not be able to do lookups correctly. You will have to go to the plugin settings in osTicket, save the changes, and see if it saves successfully.

Cheers.

**Comment by Hoimar** [comment]
Thank you for the answer, @JediKev , forgot to include that. The situation is a bit more complicated. The production OSTicket installation somehow was never updated since `v1.8-git (?)`. There, the LDAP login works, but the search does not. I'll update it soon.
On my test installation (see below), the search worked when LDAP was disabled, but when I enabled it, the search failed with the same error as on the production installation. However, it was not configured.

So I did that now and it works like a charm, the issue seems to be fixed in the later OSTicket/Plugin versions.
Environment:
```
osTicket-Version | v1.14.1 (f1e9e88) —  Aktuell
Server-Software  | Apache/2.4.41 (Win64) OpenSSL/1.1.1c PHP/7.4.2
MySQL-Version    | 10.4.11
PHP-Version      | 7.4.2
```

**Comment by JediKev** [comment]
@Hoimar 

Okay, awesome! So just to confirm, the issue is resolved for you when upgrading to a supported version?

Cheers.

**Comment by Hoimar** [comment]
@JediKev On my test installation (v 1.14.1) the user search works fine with LDAP plugin activated & configured. I think when upgrading the production installation it should work fine too, but I can not yet confirm that.

**Comment by JediKev** [comment]
@Hoimar 

Okay, keep us updated. 👍

Cheers.

**Comment by Hoimar** [comment]
@JediKev Alright, I managed to duplicate the production OSTicket VM to a test instance and then upgraded to v1.14.1 (f1e9e88). Sadly, the user search still does not work. together with the LDAP plugin, among other issues for which I should probably open separate issues:
- help topic column in ticket list is missing the topic name, only icons are displayed.
- ticket list takes very long to load (~60s), then times out, then reloads normally. After a bit of waiting it will take 60s again. This behavior started on the old installation (v1.8-git) and stays the same here. Already enabled slow query logging.

Back to the original issue. When I search a user no results are shown, the following pops up in the browser console:
`jquery-3.4.0.min.js?f1e9e88:2 GET https://<host>/scp/ajax.php/users?q=<search query> 400 (Bad Request)`
Where else could I find information abpout this error? The nginx logs in `/var/log/nginx/error.log` are empty, the corresponding `/var/log/php7.3-fpm.log` files also don't show an error. As mentioned above, the same setup works fine on a fresh OSTicket installation with LDAP plugin enabled.
```
Serverinformationen
--
osTicket-Version | v1.14.1 (f1e9e88) —  Aktuell
Server-Software | nginx/1.10.3
MySQL-Version | 10.1.44
PHP-Version | 7.3.16-1+0~20200320.56+debian9~1.gbp370a75
```

Cheers

**Comment by JediKev** [comment]
@Hoimar 

I do not see any issues when enabling the plugin and performing a search but I am using Apache instead of NGINX. With NGINX you have to make quite a few changes to the config in order for osTicket to function properly. If you do not see any errors via PHP or LDAP debug logs then I would assume that you are missing an NGINX config or something. I would try switching to Apache and retest as you do not have to do anything extra, it works right out of the box. If search works with Apache then you know the issue is with an NGINX config. In one of your previous comments you said it was working and I noticed you were using Apache so I would bet on NGINX being the culprit here but we won’t know unless you test.

Cheers.

**Comment by Hoimar** [comment]
@JediKev Thanks for the answer.
Indeed, using Apache actually made the difference, user search (also collaborators etc.) works now.
The nginx config file also looks quite complicated with a lot of allow and deny rules that seem to replace the `.htaccess` files that Apache uses. My predecessor must've copied an example "OSTicket with nginx" config from somewhere (which is bound to break with newer versions).
I'll probably stick with Apache as Nginx doesn't have any benefits for us.
What remains the same though:
- long loading times whenever a query on the ticket list is executed (this was the same in v1.8, ~60sec for a query to finish)
- the "Subject" column (help topic) in the ticket list is empty (this did work in v1.8 and is broken now)
![image](https://user-images.githubusercontent.com/36260114/78124040-63727b80-740f-11ea-81a1-ba9a39178788.png)

I'm not sure if these are bugs or problems with the config, so should I open an issue or go to the (somewhat less frequented?) forums?

**Comment by JediKev** [comment]
@Hoimar 

>long loading times whenever a query on the ticket list is executed (this was the same in v1.8, ~60sec for a query to finish)

This is dependent on how many tickets you have, the server resources, and how well MySQL is tuned/optimized. A good start would be to look at the server performance (specifically the resource usage) to see if you need to bump the RAM up or give it a better CPU/more CPU cores/etc. For now we have the ticket queries as optimized as we can get them so until we can make further progress you might have to archive tickets, beef up your server, and/or fine tune/optimize MySQL.

>the "Subject" column (help topic) in the ticket list is empty (this did work in v1.8 and is broken now)

You need to check the Primary Data Source for the Subject Column. Go to **Admin Panel > Settings > Tickets > Queues > click Open (as an example) > Columns** and click **Config** next to Subject. The **Primary Data Source** _should_ be set to **Issue Summary**. If it is set to Issue Summary then you possibly don't have enough width in the column for anything to display. So you might need to mess with the column widths as well.

>so should I open an issue or go to the (somewhat less frequented?) forums?

So Github is a place to report actual confirmed bugs with the software itself (called Issues), to create a Feature Request (also called Issues), or to submit a Pull Request. The Forum is for everything else regarding osTicket such as any questions, how-tos, etc.

Cheers.

**Comment by Hoimar** [comment]
@JediKev 
> This is dependent on how many tickets you have, the server resources, and how well MySQL is tuned/optimized. A good start would be to look at the server performance (specifically the resource usage) to see if you need to bump the RAM up or give it a better CPU/more CPU cores/etc. For now we have the ticket queries as optimized as we can get them so until we can make further progress you might have to archive tickets, beef up your server, and/or fine tune/optimize MySQL.

Okay. The VM has got 16 CPU cores @2.21GHz and 2GB of RAM (and 2GB of swap). The ram is usually at ~850MB/1.95GB. Our instance isn't used *that* heavily, so I don't think the system lacks resources.

I looked at the resource usage and saw that when executing e.g. the "Open tickets" query, MySQL spawns multiple processes which use 100% of several CPU cores, usually 2. After about 60s, a blank web page is rendered. At that time, one MySQL process remains with 100% CPU usage. If I execute the query again e.g. reload the page, it's fast as it should be. Some time after that, the process dies, but pages still load fast. After some more time, it takes very long again.

I enabled slow query logging, here's what such a log entry looks like:
```
# Time: 200402 11:30:12
# User@Host: osticket[osticket] @ localhost []
# Thread_id: 20267  Schema: osticketdb  QC_hit: No
# Query_time: 68.182214  Lock_time: 0.000299  Rows_sent: 1  Rows_examined: 17329271
# Rows_affected: 0
SET timestamp=1585819812;
SELECT COUNT(DISTINCT CASE WHEN A2.`state` = 'open' AND A2.`state` = 'open' AND A2.`state` = 'open' AND A1.`dept_id` = 1 THEN A1.`ticket_id` END) AS `q15`, COUNT(DISTINCT CASE WHEN A1.`topic_id` = 55 AND A2.`state` = 'open' THEN A1.`ticket_id` END) AS `q17`, COUNT(DISTINCT CASE WHEN B0.`value` IS NOT NULL THEN A1.`ticket_id` END) AS `q33`, COUNT(DISTINCT CASE WHEN A2.`id` IN (1) AND A1.`topic_id` = 52 THEN A1.`ticket_id` END) AS `q41`, COUNT(DISTINCT CASE WHEN A2.`state` = 'open' AND A1.`staff_id` IN (15) THEN A1.`ticket_id` END) AS `q45`, COUNT(DISTINCT CASE WHEN A1.`topic_id` = 19 AND A2.`state` = 'open' THEN A1.`ticket_id` END) AS `q46`, COUNT(DISTINCT CASE WHEN A1.`dept_id` = 1 AND A1.`duedate` BETWEEN NOW() AND (NOW() + INTERVAL '14' DAY) THEN A1.`ticket_id` END) AS `q49`, COUNT(DISTINCT CASE WHEN NOT A2.`state` = 'open' AND A1.`topic_id` = 13 AND B1.`value` IS NOT NULL THEN A1.`ticket_id` END) AS `q50`, COUNT(DISTINCT CASE WHEN A2.`id` IN (1) AND A1.`topic_id` = 52 AND A2.`id` IN (1) AND A1.`topic_id` = 52 AND A2.`id` IN (1) AND A1.`topic_id` = 23 THEN A1.`ticket_id` END) AS `q54`, COUNT(DISTINCT CASE WHEN A2.`state` = 'open' AND A1.`topic_id` = 70 THEN A1.`ticket_id` END) AS `q58`, COUNT(DISTINCT CASE WHEN NOT A2.`state` = 'open' AND A1.`dept_id` = 1 THEN A1.`ticket_id` END) AS `q60`, COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' AND A1.`topic_id` = 55 THEN A1.`ticket_id` END) AS `q63`, COUNT(DISTINCT CASE WHEN A1.`topic_id` = 43 AND B2.`value` IS NOT NULL THEN A1.`ticket_id` END) AS `q67`, COUNT(DISTINCT CASE WHEN A2.`state` = 'open' THEN A1.`ticket_id` END) AS `q1`, COUNT(DISTINCT CASE WHEN A2.`state` = 'open' AND A1.`isanswered` = '1' THEN A1.`ticket_id` END) AS `q2`, COUNT(DISTINCT CASE WHEN (A1.`team_id` IN (1, 2, 6) OR A1.`staff_id` IN (15)) AND A2.`state` = 'open' THEN A1.`ticket_id` END) AS `q3`, COUNT(DISTINCT CASE WHEN A2.`state` = 'open' AND NOT (A1.`team_id` = 0 AND A1.`staff_id` = 0) THEN A1.`ticket_id` END) AS `q5`, COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' THEN A1.`ticket_id` END) AS `q4`, COUNT(DISTINCT CASE WHEN A2.`state` = 'open' AND A2.`state` = 'open' AND A1.`isoverdue` = '1' THEN A1.`ticket_id` END) AS `q6` FROM `ost_ticket` A1 JOIN `ost_ticket_status` A2 ON (A1.`status_id` = A2.`id`) LEFT JOIN `ost_thread` A3 ON (A3.`object_type` = 'T' AND A1.`ticket_id` = A3.`object_id`) LEFT JOIN `ost_thread_referral` A4 ON (A3.`id` = A4.`thread_id`) LEFT JOIN `ost_staff` A5 ON (A4.`object_type` = 'S' AND A4.`object_id` = A5.`staff_id`) LEFT JOIN `ost_team` A6 ON (A4.`object_type` = 'E' AND A4.`object_id` = A6.`team_id`) LEFT JOIN `ost_department` A7 ON (A4.`object_type` = 'D' AND A4.`object_id` = A7.`id`) JOIN `ost_form_entry` A8 ON (A8.`object_type` = 'T' AND A1.`ticket_id` = A8.`object_id`) LEFT JOIN `ost_form_entry_values` B0 ON (A8.`id` = B0.`entry_id`) LEFT JOIN `ost_form_entry_values` B1 ON (A8.`id` = B1.`entry_id`) LEFT JOIN `ost_form_entry_values` B2 ON (A8.`id` = B2.`entry_id`) WHERE (A2.`state` = 'open' AND (A1.`staff_id` = 15 OR A5.`staff_id` = 15 OR A1.`team_id` IN (1, 2, 6) OR A6.`team_id` IN (1, 2, 6))) OR A1.`dept_id` IN (1, 5, 7, 9, 10) OR A7.`id` IN (1, 5, 7, 9, 10);
```
Quite a few examined rows...
Also, this doesn't happen to all users.
This is the number of tickets:
```
> select count(*) from ost_ticket;
+----------+
| count(*) |
+----------+
|    13281 |
+----------+
1 row in set (0.00 sec)
```


> You need to check the Primary Data Source for the Subject Column.

Ahh yes, that fixed it, thank you.

**Comment by JediKev** [comment]
@Hoimar 

Looks like you’ll need to fine tune MySQL and bump up the server resources.

Cheers.

**Comment by Hoimar** [comment]
@JediKev So I wanted to report back on this old issue. In the meantime, I managed to upgrade our production OSTicket installation to v1.14.2 and tweak MySQL and performance is better now. Regardless if there is an underlying issue, load times have reduced from >30s to about 5-10s for large queues now which is much better and doesn't hinder user experience. If I read the changelogs correctly, quite a few performance optimizations have been made between our old version (1.8) and the newer ones.

Perhaps this issue can be closed now?

Anyway, thanks for building such a nice open source project.
