### ISSUE TITLE
Unable to assign ticket after upgrade

### ISSUE THREAD

**Issue by cervedgroup** [osTicket/osTicket#5552]
Web Server Software | Microsoft-IIS/8.5
MySQL | 10.3.14
PHP | 5.6

just moved from v1.10.7 to latest version 1.14.2

i'm testing all the stuff after the upgrade, now i'm unable to assign a ticket assigned to me to another operator

![84292895-49f45b00-ab47-11ea-8eaa-5276f2a53516](https://user-images.githubusercontent.com/6535381/84771189-3f1f4780-afd9-11ea-89cf-606a8817234f.png)

if a claim an unassigned ticket , i can assign it to other operators ... the problem seems only for ticket already assigned to me before the upgrade

problem is present for all operators , not only my account ...

maybe if the smtp server is unreachable, the ticket reassigning fails ? our test server has no access to the mail server

**Comment by xhit** [comment]
PHP version 7.0 to 7.3 should be used for osTicket 1.14.2.

Also share your System Logs.

> maybe if the smtp server is unreachable, the ticket reassigning fails ? our test server has no access to the mail server

Isn't necessary, if SMTP server cannot be reached a Log is inserted in System Logs.

**Comment by cervedgroup** [comment]
@xhit , updated to 7.3 php , same error...
this is the system log error entry
![image](https://user-images.githubusercontent.com/6535381/84868164-8e6a8400-b07c-11ea-853d-a3d975a47c4c.png)

if i manually run the query on the db : 
select * from ost_ticket WHERE 'ost_ticket'.'ticket_id' = 356716 LIMIT 1 
i get the correct result with no erorrs

if i manually run the query 
UPDATE `ost_ticket` SET `staff_id` = 2, `updated` = NOW() WHERE `ost_ticket`.`ticket_id` = 356716 LIMIT 1

got same error #1054 

also many other #1054 errors are present in system logs
![image](https://user-images.githubusercontent.com/6535381/84868743-72b3ad80-b07d-11ea-866e-4f6efa365c1d.png)

alre all updates that fails with "Unknow column 'state' in where clause'

**Comment by xhit** [comment]
What columns do you have in `ost_thread_event` table?

In osTicket 1.10.x exists the `state` column, but not in 1.14.x. The only table with this column in 1.14.x is `ost_ticket_status` and exists before 1.10.x. So, your osTicket maybe is not fully upgraded.

Note:
I recommend from users that want upgrade from 1.10.x to 1.14.x, first upgrade to 1.12.x, I had similar problems upgrading from 1.10 to 1.14.2 directly and were solved upgrading 1.10->1.12.x->1.14.2

From 1.12.x to 1.14.2, I recommend use php version 7.2+

Note2:
Never exec queries errors in System Logs, some of them are malformed without a `where` clause and will affect all rows.

I'm not a osTicket developer, but I manage the osTicket in 3 business with custom features, so maybe this recommendations will help.

**Comment by JediKev** [comment]
@cervedgroup 

Yea, I don't see the `state` column in the query at all. 🤔 Either something went wrong during the upgrade or you need to restart the webserver, restart MySQL, clear your cache, and retest.

Cheers.

**Comment by cervedgroup** [comment]
@JediKev i've restarted all the server, the update process didn't gave me any errors but the problem is still in place  ... i'll try the @xhit suggestion ...
