### ISSUE TITLE
OsTicket 1.16.3 image upload error while opening new ticket via frontend

### ISSUE THREAD

**Issue by prbt2016** [osTicket/osTicket#6174]
### Description

[Description of the bug or feature]

I was in the process of manual installation of OsTicket 1.16.3 on Centos 7 with PHP 8, MYSQL 5.5, Apache 2.2 . 

However, the following error is thrown while Uploading image from frontend while selecting the option i.e 'Open a new ticket' using  'Drop files here or choose them ' , following is the error thrown while doing the same : 

File Upload Error:
example.jpg
undefined500

Also following is the screenshot of the same : 

![test](https://user-images.githubusercontent.com/17871448/169470476-b7df5adf-2bf8-476d-acf1-afcd638f792b.jpg)

### Steps to Reproduce

1.  Visit Open New ticket from Frontend
2.  Select any of the help topic from the select list
3.  Go to Drop files here or choose them and upload image and the above error is thrown.

**Expected behavior:** 
Image should be uploaded successfully

**Actual behavior:** File Upload Error undefined 500

### Versions
OS : Centos 7
Browser ; 100.0.1 (64-bit)
OsTicket version : 1.16.3
PHP version : PHP8
MYSQL version : MYSQL 5.5
Apache version : 2.2

What could be causing the issue?. Could you please replicate this issue at your end ?.

**Comment by ntozier** [comment]
I would invite you to seek your support experience on the support forums.  
Github is more for bug reports.
https://forum.osticket.com/

That being said since you are using CentOS - are you running SELinux?
Running any storage plugins?
HAve you defined allowed attachment types? (**Admin panel -> Settings -> Tickets**... scroll down to Attachments, click the Config button)

**Comment by prbt2016** [comment]
Hello @ntozier,

Thanks for your reply.

> That being said since you are using CentOS - are you running SELinux?

No. It is disabled. Here is the output of `sestatus` command 

![test](https://user-images.githubusercontent.com/17871448/169539150-2e17adcb-6ee6-4f62-8cbd-b9cd47975090.jpg)

> Running any storage plugins?

No.

HAve you defined allowed attachment types? (Admin panel -> Settings -> Tickets... scroll down to Attachments, click the Config button)
No.

I am using default installation procedure of OSticket and this is a fresh install of OSticket 1.16.3. 
I have not made any changes to the same.

Regards.

**Comment by ntozier** [comment]
Can you try going to **Admin panel -> Settings -> Tickets**
scroll down to Attachments, 
click the Config button

add the .ext of the file type that you want to allow. 
Save and retest for me.

**Comment by prbt2016** [comment]
Hello @ntozier ,

Was able to upload .jpg, .png , .gif after adding them from Admin panel -> Settings -> Tickets -> Attachments -> Ticket Attachment Settings -> Config -> Field setup ->  Additional File Type Filters

Then Adding .jpg, .png , .gif to the same and click 'Save'.

Here's the screenshot below.

![image](https://user-images.githubusercontent.com/17871448/169740080-bfbdf49f-a7f8-4219-8932-953650a24a2a.png)

Then I tested from Open a new ticket -> 'Drop files here or choose them ' and uploaded those same file types i.e .jpg, .png , .gif that works fine .

**Comment by stevland** [comment]
I'm also seeing this issue.

It doesn't occur in 1.15.7, but it occurs in 1.16 onwards.

I am also on CentOS, and I turned off SELinux to no avail.

My 1.15.7 installation uses PHP 7.2.34. My 1.16.x installations use PHP 8.0.19.

The problem occurs in both the Client and Staff forms, and with both _drag and drop_ and _browse_ operations.

The errors I saw in DevTools all referenced `filedrop.field.js`.

But once I added **Additional File Type Filters** everything worked as expected for me, too.

Until this is fixed, here are the filetypes I'm using as a workaround (this list took me a while to put together so hopefully it will help other people):

`.3g2,.3gp,.7z,.ai,.aif,.arj,.asp,.aspx,.avi,.bak,.bin,.bmp,.cab,.cda,.cer,.cfg,.cfm,.cgi,.cpl,.css,.csv,.cur,.dat,.dat,.db,.db,.dbf,.dbf,.deb,.dll,.dmg,.dmp,.doc,.docx,.flv,.fnt,.fon,.gif,.gz,.h264,.htm,.html,.icns,.ico,.ico,.ini,.iso,.jpeg,.jpg,.js,.jsp,.lnk,.log,.log,.m4v,.mdb,.mdb,.mid,.midi,.mkv,.mov,.mp3,.mp4,.mpa,.mpeg,.mpg,.msi,.ods,.odt,.ogg,.otf,.part,.pdf,.php,.pkg,.pl,.png,.ps,.psd,.py,.rar,.rm,.rpm,.rss,.rtf,.sav,.sav,.sql,.sql,.svg,.swf,.sys,.tar,.tar,.tar,.tex,.tif,.tiff,.tmp,.toast,.ttf,.txt,.vcd,.vob,.wav,.wma,.wmv,.wpd,.wpl,.xhtml,.xls,.xlsm,.xlsx,.xml,.xml,.z,.zip`

**Comment by prbt2016** [comment]
Hello @ntozier ,

Any updates regarding the same ?.

Regards.

**Comment by ntozier** [comment]
@prbt2016 I'm not a Dev so I do not have an update.  I was just suggesting a workaround.  Which Stevland expanded upon.

**Comment by prbt2016** [comment]
Hello @JediKev ,

Could you please look into the above issue ?. And possibly fix this through code, it would be great. As many users would have this issue while creating a ticket, when they try to upload images. 

Kindly let me know.

Regards.

**Comment by drzhouq** [comment]
There are a few things can be involved. 1) go to your admin user interface, "settings", make sure you have the size limit correct; 2) go to the "tickets", make sure the custom field (file drop) is enabled for users, default is not if the ticket submitter is not registered.

**Comment by JediKev** [comment]
@prbt2016 

I was able to replicate this issue using Apache, v1.16.3, and PHP 8.0.x but the caveat is this was upgraded from v1.6 so the `configuration` value for the Issue Details field was missing in the database. I still need to test this with fresh installs to see if this is an actual bug or not.

The way I fixed this is to simply go to **Admin Panel > Mange > Forms > Ticket Details**, click **Config** next to **Issue Details**, and click **Save**. This should update the database and add a `size` config where the system should then be able to verify the attachment size is less than or equal to what's configured in the Field configuration.

Cheers.

**Comment by prbt2016** [comment]
@JediKev ,

Thanks for looking into the issue . Kindly test this for fresh installs of 1.16.3 as well . Many users might face the same issue on a fresh install. It would be really great if you could fix  this by code as users won't have to manually enter the extensions each time an issue occurs while uploading an image.

Kindly let me know if you discover the issue on fresh installs . 

Regards.

**Comment by stevland** [comment]
I've been playing around with the dropzone / embedded upload function in 1.17 and I found that the situation is _somewhat_ fixed, but it still isn't very intuitive.

I used .png and .pdf files in my tests. I didn't have anything added to _Additional Filetype Filters_.

I found that in the Staff Panel, by default, one can attach both .png and .pdf files up to ~8MBs.

This is in spite of the fact that **Agent Panel** > **Tickets** > **Ticket Settings and Options** > **Ticket Attachment Settings** > **Maximum File Size** is set to 128 MB.

And in the Client Portal, by default, one can upload .png files up to ~1MB. But one cannot upload .pdf files at all.

**Comment by JediKev** [comment]
@stevland 

I have a pull coming today that might fix this issue.

Cheers.

**Comment by stevland** [comment]
@JediKev I can't believe how quickly you replied.

If I may offer a suggestion...

It would be quite useful -- at least in the Client Portal -- to have text in the Dropzone specifying which filetypes are allowed.

**Comment by stevland** [comment]
@JediKev I can't believe how quickly you replied. Thank you.

If I may offer a suggestion...

It would be quite useful -- at least in the Client Portal -- to have text in the Dropzone specifying which filetypes are allowed.

**Comment by JediKev** [comment]
@stevland 

Okay, below is the pull request:
- https://github.com/osTicket/osTicket/pull/6308

I'll try to explain the issue the best I can. So the real issue is not with the configured file types, instead, it's due to the field `configuration` in the database not being set. You see, if you've never touched the configuration for the Issue Details field (or any custom FileUploadField) the `configuration` is not set in the database. So once you add a file type and save the `configuration` will be generated and saved in the database properly. So the real issue is since there is no `configuration` we don't have a `size` option in the field's config. So when you upload a file we compare the uploaded file's size against the allowed file size from the field's config and since there is no `size` it fails. So applying the pull request above will check for the `size` in the config and if not set then we will default to 1 MB.

If you want your users to be able to upload any file type you can completely remove the additional file type filters and the file restrictions and they should be able to upload anything.

Also, I don't think adding allowed file types  to the field itself for display will be ideal as it can get very long and look very weird/messy when rendering. We do set the allowed file types in the config of the upload field so when users go to upload files their file browser should be restricted to such file types automatically. It shouldn't allow them to select anything other than the allowed file types.

Cheers.
